micronaut:
  application:
    name: demo

netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/cscore`}
    username: ${JDBC_USER:cscore}
    password: ${JDBC_PASSWORD:cscore}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

hibernate.jdbc.time_zone: UTC

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: ${SHOW_SQL:false}